name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - name: Setup Git
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.RELEASE_GH_TOKEN }}
    - name: Configure Git
      env:
        GH_USER_EMAIL: ${{ secrets.RELEASE_GH_EMAIL }}
        GH_USER_NAME: ${{ secrets.RELEASE_GH_USERNAME }}
      run: |
        git fetch --prune --unshallow --tags --force
        git config user.email "$GH_USER_EMAIL"
        git config user.name "$GH_USER_NAME"
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Node Packages
      run: |
        yarn install
        yarn lock:check
    - name: Build
      run: yarn build
    - name: Lint
      run: yarn lint
    - name: Test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        yarn test:coverage
        yarn report:coverage
    - name: Release
      run: yarn release
      if: matrix.node-version == '12.x' && github.ref == 'refs/heads/master'
