name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Setup ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        yarn install
        yarn lock:check
    - name: Build
      run: yarn build
    - name: Lint
      run: yarn lint
    - name: Test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        yarn test:coverage
        yarn report:coverage
    - name: Deploy
      env:
        GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn release
      if: matrix.node-version == '12.x' && github.ref == 'refs/heads/master'
